CREATE TABLE "MEMBER" (
	"MEMBER_NO"	NUMBER		NOT NULL,
	"ID"	VARCHAR2(10)		UNIQUE NOT NULL,
	"PASSWORD"	VARCHAR2(20)		NOT NULL,
	"NAME"	VARCHAR2(10)		NOT NULL,
	"EMAIL"	VARCHAR2(30)		UNIQUE NOT NULL,
	"CREATE_AT"	DATE	DEFAULT SYSDATE	NOT NULL,
	"DELETE_AT"	DATE	DEFAULT SYSDATE	NULL
);

CREATE SEQUENCE "MEMBER_NO_SEQ" 
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOORDER
NOCYCLE;


CREATE TABLE "SPACE" (
	"SPACE_NO"	NUMBER		NOT NULL,
	"SPACE_NAME"	VARCHAR2(40)	DEFAULT 새 워크스페이스	NULL,
	"MANAGER_NO"	NUMBER		NOT NULL
);


CREATE SEQUENCE "SPACE_NO_SEQ" 
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOORDER
NOCYCLE;

CREATE TABLE "SPACE_MEMBER" (
	"SPACE_MEMBER_NO"	NUMBER		NOT NULL,
	"SPACE_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);


CREATE SEQUENCE "SPACE_MEMBER_NO_SEQ" 
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOORDER
NOCYCLE;

CREATE TABLE "INVITE" (
	"INVITE_NO"	NUMBER		NOT NULL,
	"SPACE_NO"	NUMBER		NOT NULL,
	"MEMBER_NO"	NUMBER		NOT NULL
);


CREATE SEQUENCE "INVITE_NO_SEQ" 
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOORDER
NOCYCLE;

CREATE TABLE "ROOM" (
	"ROOM_NO"	NUMBER		NOT NULL,
	"SPACE_NO"	NUMBER		NOT NULL,
	"ROOM_NAME"	VARCHAR2(20)	DEFAULT 새 그룹 채팅방	NULL
);


CREATE SEQUENCE "ROOM_NO_SEQ" 
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOORDER
NOCYCLE;

CREATE TABLE "ROOM_MEMBER" (
	"ROOM_MEMBER_NO"	NUMBER		NOT NULL,
	"ROOM_NO"	NUMBER		NOT NULL,
	"SPACE_MEMBER_NO"	NUMBER		NOT NULL,
	"IN_TIME"	DATE	DEFAULT SYSDATE	NULL,
	"OUT_TIME"	DATE	DEFAULT SYSDATE	NULL
);


CREATE SEQUENCE "ROOM_MEMBER_NO_SEQ" 
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOORDER
NOCYCLE;

CREATE TABLE "PCHAT" (
	"PCHAT_NO"	NUMBER		NOT NULL,
	"ROOM_NO"	NUMBER		NOT NULL,
	"SPACE_MEMBER_NO"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(3000)		NULL,
	"FILENAME"	VARCHAR2(50)		NULL,
	"SPACE_MEMBER_RE_NO"	NUMBER		NULL,
	"RE_CONTENT"	VARCHAR2(3000)		NULL,
	"CREATE_AT"	DATE	DEFAULT SYSDATE	NOT NULL
);


CREATE SEQUENCE "PCHAT_NO_SEQ" 
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOORDER
NOCYCLE;

CREATE TABLE "GCHAT" (
	"GCHAT_NO"	NUMBER		NOT NULL,
	"ROOM_NO"	NUMBER		NOT NULL,
	"SPACE_MEMBER_NO"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(3000)		NULL,
	"FILENAME"	VARCHAR2(50)		NULL,
	"SPACE_MEMBER_RE_NO"	NUMBER		NULL,
	"RE_CONTENT"	VARCHAR2(3000)		NULL,
	"CREATE_AT"	DATE	DEFAULT SYSDATE	NOT NULL
);


CREATE SEQUENCE "GCHAT_NO_SEQ" 
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOORDER
NOCYCLE;

CREATE TABLE "AL_ROOM" (
	"AL_ROOM_NO"	NUMBER		NOT NULL,
	"SPACE_NO"	NUMBER		NOT NULL,
	"SPACE_MEMBER_NO"	NUMBER		NOT NULL,
	"IN_TIME"	DATE	DEFAULT SYSDATE	NULL,
	"OUT_TIME"	DATE		NULL
);


CREATE SEQUENCE "AL_ROOM_NO_SEQ" 
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOORDER
NOCYCLE;

CREATE TABLE "AL_CHAT" (
	"AL_CHAT_NO"	NUMBER		NOT NULL,
	"AL_ROOM_NO"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(1000)		NOT NULL,
	"CREATE_AT"	DATE	DEFAULT SYSDATE	NOT NULL
);


CREATE SEQUENCE "AL_CHAT_NO_SEQ" 
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOORDER
NOCYCLE;

CREATE TABLE "BOARD" (
	"BOARD_NO"	NUMBER		NOT NULL,
	"SPACE_NO"	NUMBER		NOT NULL
);


CREATE SEQUENCE "BOARD_NO_SEQ" 
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOORDER
NOCYCLE;

CREATE TABLE "BOARD_DETAIL" (
	"BOARD_DETAIL_NO"	NUMBER		NOT NULL,
	"BOARD_NO"	NUMBER		NOT NULL,
	"SPACE_MEMBER_NO"	NUMBER		NOT NULL,
	"SUBJECT"	VARCHAR2(60)		NOT NULL,
	"CONTENT"	VARCHAR2(3000)		NOT NULL,
	"FILENAME"	VARCHAR2(50)		NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NOT NULL
);


CREATE SEQUENCE "BOARD_DETAIL_NO_SEQ" 
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOORDER
NOCYCLE;

CREATE TABLE "BROWSER" (
	"BROWSER_NO"	NUMBER		NOT NULL,
	"SPACE_NO"	NUMBER		NOT NULL
);


CREATE SEQUENCE "BROWSER_NO_SEQ" 
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOORDER
NOCYCLE;

CREATE TABLE "BROWSER_DETAIL" (
	"BROWSER_DETAIL_NO"	NUMBER		NOT NULL,
	"BROWSER_NO"	NUMBER		NOT NULL,
	"SPACE_MEMBER_NO"	NUMBER		NOT NULL,
	"FILENAME"	VARCHAR2(50)		NOT NULL,
	"UPLOAD_TIME"	DATE		NOT NULL
);


CREATE SEQUENCE "BROWSER_DETAIL_NO_SEQ" 
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOORDER
NOCYCLE;

CREATE TABLE "F_CALLENDER" (
	"F_CALLENDER_NO"	NUMBER		NOT NULL,
	"SPACE_NO"	NUMBER		NOT NULL
);


CREATE SEQUENCE "F_CALLENDER_NO_SEQ" 
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOORDER
NOCYCLE;

CREATE TABLE "F_CALLENDER_DETAIL" (
	"FC_DETAIL_NO"	NUMBER		NOT NULL,
	"F_CALLENDER_NO"	NUMBER		NOT NULL,
	"SPACE_MEMBER_NO"	NUMBER		NOT NULL,
	"SUBJECT"	VARCHAR2(50)	DEFAULT 새 캘린더	NULL,
	"EVENT_START_DATE"	DATE		NOT NULL,
	"EVENT_END_DATE"	DATE		NOT NULL,
	"CONTENT"	VARCHAR2(200)		NOT NULL
);

CREATE SEQUENCE "FC_DETAIL_NO_SEQ" 
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOORDER
NOCYCLE;

CREATE TABLE "KANBAN" (
	"KANBAN_NO"	NUMBER		NOT NULL,
	"SPACE_NO"	NUMBER		NOT NULL
);


CREATE SEQUENCE "KANBAN_NO_SEQ" 
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOORDER
NOCYCLE;

CREATE TABLE "KANBAN_DETAIL" (
	"KANBAN_DETAIL_NO"	NUMBER		NOT NULL,
	"KANBAN_NO"	NUMBER		NOT NULL,
	"SPACE_MEMBER_NO"	NUMBER		NOT NULL,
	"CONTENT"	VARCHAR2(60)		NOT NULL,
	"STATUS"	VARCHAR2		NOT NULL,
	"UPDATE_DATE"	DATE	DEFAULT SYSDATE	NULL,
	"CREATE_DATE"	DATE	DEFAULT SYSDATE	NULL
);


CREATE SEQUENCE "KANBAN_DETAIL_NO_SEQ" 
START WITH 1
INCREMENT BY 1
MAXVALUE 99999
NOCACHE
NOORDER
NOCYCLE;


ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"MEMBER_NO"
);

ALTER TABLE "SPACE" ADD CONSTRAINT "PK_SPACE" PRIMARY KEY (
	"SPACE_NO"
);

ALTER TABLE "SPACE_MEMBER" ADD CONSTRAINT "PK_SPACE_MEMBER" PRIMARY KEY (
	"SPACE_MEMBER_NO"
);

ALTER TABLE "INVITE" ADD CONSTRAINT "PK_INVITE" PRIMARY KEY (
	"INVITE_NO"
);

ALTER TABLE "ROOM" ADD CONSTRAINT "PK_ROOM" PRIMARY KEY (
	"ROOM_NO"
);

ALTER TABLE "ROOM_MEMBER" ADD CONSTRAINT "PK_ROOM_MEMBER" PRIMARY KEY (
	"ROOM_MEMBER_NO"
);

ALTER TABLE "PCHAT" ADD CONSTRAINT "PK_PCHAT" PRIMARY KEY (
	"PCHAT_NO"
);

ALTER TABLE "GCHAT" ADD CONSTRAINT "PK_GCHAT" PRIMARY KEY (
	"GCHAT_NO"
);

ALTER TABLE "AL_ROOM" ADD CONSTRAINT "PK_AL_ROOM" PRIMARY KEY (
	"AL_ROOM_NO"
);

ALTER TABLE "AL_CHAT" ADD CONSTRAINT "PK_AL_CHAT" PRIMARY KEY (
	"AL_CHAT_NO"
);

ALTER TABLE "BOARD" ADD CONSTRAINT "PK_BOARD" PRIMARY KEY (
	"BOARD_NO"
);

ALTER TABLE "BOARD_DETAIL" ADD CONSTRAINT "PK_BOARD_DETAIL" PRIMARY KEY (
	"BOARD_DETAIL_NO"
);

ALTER TABLE "BROWSER" ADD CONSTRAINT "PK_BROWSER" PRIMARY KEY (
	"BROWSER_NO"
);

ALTER TABLE "BROWSER_DETAIL" ADD CONSTRAINT "PK_BROWSER_DETAIL" PRIMARY KEY (
	"BROWSER_DETAIL_NO"
);

ALTER TABLE "F_CALLENDER" ADD CONSTRAINT "PK_F_CALLENDER" PRIMARY KEY (
	"F_CALLENDER_NO"
);

ALTER TABLE "F_CALLENDER_DETAIL" ADD CONSTRAINT "PK_F_CALLENDER_DETAIL" PRIMARY KEY (
	"FC_DETAIL_NO"
);

ALTER TABLE "KANBAN" ADD CONSTRAINT "PK_KANBAN" PRIMARY KEY (
	"KANBAN_NO"
);

ALTER TABLE "KANBAN_DETAIL" ADD CONSTRAINT "PK_KANBAN_DETAIL" PRIMARY KEY (
	"KANBAN_DETAIL_NO"
);

